### PR TITLE
Updated AppVeyor build

### PR DESCRIPTION
**Pull request by jozefizso**
The AppVeyor build will compile all projects and run .NET and C++ tests in both Release and Debug configurations.

The Release build will also create NuGet package.

### CODE REVIEW

**Comment by mmaitre314** [comment]
I added you as contributor so you can make changes as you see fit. I haven't been working on that project for a while, so at this point you know the code at least as well as I remember it... One small update that would be useful is putting an example of channel in use in readme.md.

**Comment by jozefizso** [comment]
Thanks, Matthieu. I have update the documentation to include Channels.

Can you also make me a contributor for the NuGet package, so I can publish a new version?

**Comment by mmaitre314** [comment]
What is your username on nuget.org?

**Comment by jozefizso** [comment]
It's jozef.izso

**Comment by mmaitre314** [comment]
You are owner on that package.

**Comment by jozefizso** [comment]
Thanks a lot, I appreciate it.

**Pull request merged**
